/**
 * Invoice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Invoice } from './invoice';


export interface InvoiceItem { 
    id?: number;
    invoice?: Invoice;
    orderId?: string;
    description?: string;
    type: string;
    timeSpent?: number;
    price: number;
    serviceDateStart?: string;
    serviceDateEnd?: string;
}

